### PR TITLE
Add a feature to not show the date on posts/pages

### PR DESCRIPTION
**Pull request by jolexa**
This should be self explanatory, let me know if there are any questions. (Naming is arbitrary from me)

### CODE REVIEW

**Comment by ethanmad** [comment]
Implemented in `master` of [ethanmad/vienna](https://github.com/ethanmad/vienna).

**Comment by ethanmad** [comment]
This doesn't hide the date from the article list. For example, your "About Me / Contact" post shows "Posted on Jan 1, 0001" (seen at https://blog.jolexa.net/page/30/).

**Comment by jolexa** [comment]
Ah, didn't see that before.

**Comment by ethanmad** [comment]
@jolexa Only noticed it because I don't have multiple pages of posts. Anyway, a fix would be great. :smiley:

**Pull request merged**
