### PR TITLE
Added 15px of padding so social icons are not flush against the bottom o...

### PR DESCRIPTION
**Pull request by icecreammatt**
...f the header

I added this 15px of padding below the social icons in the banner image. I thought it looked a bit better than it being flush against the white line.

### CODE REVIEW

**Comment by keichi** [comment]
Hi, thanks for your work here. Could you provide a screenshot and your browser environment? I did not fully understand what  "being flush against the white line" means. FYR, it looks like the below screenshot with my OSX Yosemite + Chrome 41.

screen shot 2015-03-31 at 23 13 05

**Comment by icecreammatt** [comment]
You're welcome. I love your theme and figured I'd give back a bit to it. I tested in Firefox. I'll get you a screenshot in a bit.

**Comment by icecreammatt** [comment]
I made another tweak since when testing my first fix in Chrome I noticed it was basically doubling the padding. By adding that 1px padding-bottom that fixes the issue in Firefox and brings it in line with Chrome.

Firefox left, Chrome right

> Here is what it looked like before:

screen shot 2015-03-31 at 12 05 33 pm

> And this is what it looks like with the second fix I just made:

screen shot 2015-03-31 at 1 11 20 pm

**Comment by icecreammatt** [comment]
For your reference this is how your current site looks in Firefox.

screen shot 2015-03-31 at 1 15 52 pm

**Comment by keichi** [comment]
Thanks for pointing this out! I only tested on Chrome and Safari and no other browsers. Always do not forget cross-browser compatibility check...

**Pull request merged**
