### PR TITLE
added ability to change the top image for each post

### PR DESCRIPTION
**Pull request by mapitman**
just add an "image" parameter in the front matter of your post

### CODE REVIEW

**Comment by icecreammatt** [comment]
:+1:

**Comment by ethanmad** [comment]
:+1:
Might as well make the top image changeable from `config.toml`, too.

Also thanks for teaching me that if-else logic is possible in Hugo.

**Comment by mapitman** [comment]
I just found out about Hugo earlier this week, so I am learning a lot too!

**Comment by ethanmad** [comment]
One more change I would like to make Vienna more personalized is changing the link color to themecolor (if themecolor is defined). I don't know how to do this, though--can we access themecolor in a css file? I think the link color is determined by [`main.css`](https://github.com/keichi/vienna/blob/ff7b17393a8da8919c435fd6414b0260a00a7baf/static/css/main.css). (When I say link color, I mean the one that's blue by default and brown on @icecreammatt's site). 

It's a similar change to this and I'm sure you know better than I do.

**Comment by mapitman** [comment]
I added paging to the theme as well. Let me know if you are going to accept this pull request. Otherwise, I'll create a new theme based off of yours if you don't want these features added.

**Comment by keichi** [comment]
@mapitman Thanks for helping out! Sorry for the late merge...

**Pull request merged**
